#!/bin/bash

# git
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gc!='git commit -v --amend'
alias gc='git commit -v'
alias gca!='git commit -v -a --amend'
alias gca='git commit -v -a'
alias gd='git diff'
alias gds='git diff --staged'
alias gl='git pull'
alias gp='git push'
alias gpf!='git push --force'
alias gpt='git push --tag'
alias gst='git status'
alias gco='git checkout'
alias gcob='git checkout -b'
alias grst='git reset'

# ls
alias l='ls -lh'
alias ll='ls -Alh'
alias ls='ls --color'

alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'

# lazygit
# https://github.com/jesseduffield/lazygit
alias lg='lazygit'

# zigup
# https://github.com/marler8997/zigup
alias zigup="zigup --install-dir $HOME/.zigup/ --path-link $HOME/.local/bin/zig"

alias hx="helix"
