#!/usr/bin/env zsh

# ls
alias l='ls -lh'
alias ll='ls -Alh'
alias ls='ls --color'

alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'

# lazygit
# https://github.com/jesseduffield/lazygit
alias lg='lazygit'

# zigup
# https://github.com/marler8997/zigup
alias zigup="zigup --install-dir $HOME/.zigup/ --path-link $HOME/.local/bin/zig"

# helix
alias hx='helix'

# lf but show hidden dirs
alias llf="lf -command 'set hidden'"

# ide (zellij)
alias zz='zellij'
