# https://github.com/helix-editor/helix/issues/1896
[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-ls"]

[[language]]
name = "css"
file-types = ["css", "scss", "less", "pcss", "postcss"]

[[language]]
name = "gdscript"
language-servers = ["godot"]

[language-server.godot]
command = "tcp-language-server"
args = ["127.0.0.1", "6005"]

[[language]]
name = "php"
language-servers = ["phpactor"]

[language-server.phpactor]
command = "phpactor"
args = ["language-server", "-q"]
