[default_apps]
teams = "teams-for-linux --enable-features=UseOzonePlatform --ozone-platform=wayland --url {meeting_url}"
calendar_client = "thunderbird"
terminal = "ghostty"
browser = "/usr/bin/google-chrome-stable %U"

[units]
lengths = "meters"
weights = "kg"
volumes = "l"
temperatures = "C"
currency = "eur"

[debug]
try_suppress_errors = false
try_suppress_warnings = false
app_paths = []

[appearance]
width = 900
height = 593
gsk_renderer = "cairo"
icon_size = 22
use_base_css = true
opacity = 1.0
mod_key_ascii = ["⇧", "⇧", "CTRL", "⌘", "⎇", "✦", "✦", "⌘"]

[behavior]
use_xdg_data_dir_icons = false
animate = false

[files]
fallback = "~/.config/sherlock/fallback.json"

[runtime]
multi = false
center = false
photo_mode = false
display_raw = false
daemonize = false

[caching]
enable = true
cache = "~/.cache/sherlock/sherlock_desktop_cache.json"

[expand]
enable = false
edge = "top"
margin = 0

[backdrop]
enable = true
opacity = 0.6
edge = "top"

[status_bar]
enable = false

[search_bar_icon]
enable = true
icon = "system-search-symbolic"
icon_back = "go-previous-symbolic"
size = 22
